name: Java CI with Maven

on:
  push:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload to Release
      run: ls -l
#       if: github.event_name == 'release'
#       uses: RedCrabVb/DevOpsApp@master
#       with:
#         args: target/DevOpsApp-1.0-SNAPSHOT.jar application/java-archive
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
